server:
  port: 8090
  servlet:
    contextPath: /testEurekaServer

USER: root
PASSWORD: 123456

eureka:
  security:
    user:
      name: ${USER}
      password: ${PASSWORD}
  dashboard:
    path: /dashboard
    enabled: true
  instance:
    hostname: 192.168.1.30
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 50000 #清理间隔(单位毫秒,默认是60*1000)
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${USER}:${PASSWORD}@192.168.1.30/testEurekaServer/eureka
 
spring:
  application:
    name: testEurekaServer
  freemarker:
    prefer-file-system-access: false
  jmx: 
    default-domain: testEurekaServer