server:
  port: 8090
  servlet:
    contextPath: /testEurekaServer

eureka:
  dashboard:
    path: /dashboard
    enabled: true
  instance:
    hostname: 192.168.1.30
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 50000 #清理间隔(单位毫秒,默认是60*1000)
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.1.30/testEurekaServer/eureka
 
spring:
  security:
    user:
      name: admin
      password: admin
  application:
    name: testEurekaServer
  jmx: 
    default-domain: testEurekaServer